from typing import Optional
from pydantic import BaseModel, Field
from datetime import datetime

class ReviewBase(BaseModel):
    rating: int = Field(..., ge=1, le=5)  # Rating must be between 1 and 5
    title: str = Field(..., min_length=1)  # Title must not be empty
    comment: Optional[str] = Field(default=None, max_length=500)  # Optional comment with max length of 500 characters

class ReviewCreate(ReviewBase):
    pass

class Review(ReviewBase):
    created_at: datetime  # Timestamp of when the review was created, auto-generated by the database
    updated_at: datetime  # Timestamp of when the review was last updated, auto-generated by the database
